------------- Graf 1 ------------------------
SELECT
    STORE_NAME,
    TOTAL_REVENUE,
    TOTAL_TICKETS,
    DENSE_RANK() OVER (ORDER BY TOTAL_REVENUE DESC) AS STORE_RANK
FROM (
    SELECT
        s.NAME AS STORE_NAME,
        COUNT(f.TICKET_NUMBER) AS TOTAL_TICKETS,
        SUM(f.NET_PAID) AS TOTAL_REVENUE
    FROM FACT_STORE_SALES f
    JOIN STORE s
      ON f.STORE_ID = s.STORE_ID
    GROUP BY s.NAME
) t
ORDER BY STORE_RANK;

------------- Graf 2 ------------------------
SELECT
    CATEGORY_NAME,
    TOTAL_TICKETS,
    TOTAL_REVENUE,
    DENSE_RANK() OVER (ORDER BY TOTAL_TICKETS DESC) AS CATEGORY_RANK
FROM (
    SELECT
        i.CATEGORY AS CATEGORY_NAME,
        COUNT(f.TICKET_NUMBER) AS TOTAL_TICKETS,
        SUM(f.NET_PAID) AS TOTAL_REVENUE
    FROM FACT_STORE_SALES f
    JOIN DIM_ITEM i
      ON f.ITEM_ID = i.ITEM_ID
    GROUP BY i.CATEGORY
) t
ORDER BY CATEGORY_RANK
LIMIT 10;


------------- Graf 3 ------------------------
SELECT
  CUSTOMER_ID,
  PURCHASE_SEQ_IN_CUSTOMER,
  NET_PAID,
  SUM(COALESCE(NET_PAID,0)) OVER (
    PARTITION BY CUSTOMER_ID
    ORDER BY PURCHASE_SEQ_IN_CUSTOMER
  ) AS RUNNING_CUSTOMER_SPEND
FROM FACT_STORE_SALES
LIMIT 1000;

------------- Graf 4 ------------------------
SELECT
    SPENDING_GROUP,
    COUNT(*)            AS CUSTOMER_COUNT,
    MIN(TOTAL_SPENT)    AS MIN_SPENT,
    MAX(TOTAL_SPENT)    AS MAX_SPENT,
    AVG(TOTAL_SPENT)    AS AVG_SPENT
FROM (
    SELECT
        CUSTOMER_ID,
        SUM(COALESCE(NET_PAID, 0)) AS TOTAL_SPENT,
        NTILE(3) OVER (ORDER BY SUM(COALESCE(NET_PAID, 0)) DESC) AS SPENDING_GROUP
    FROM FACT_STORE_SALES
    GROUP BY CUSTOMER_ID
) t
GROUP BY SPENDING_GROUP
ORDER BY SPENDING_GROUP;

------------- Graf 5 ------------------------
SELECT
    CUSTOMER_ID,
    TICKET_NUMBER,
    NET_PAID AS CURRENT_SPENT,
    LAG(NET_PAID) OVER (
        PARTITION BY CUSTOMER_ID
        ORDER BY TICKET_NUMBER
    ) AS PREVIOUS_SPENT,
    NET_PAID - LAG(NET_PAID) OVER (
          PARTITION BY CUSTOMER_ID
          ORDER BY TICKET_NUMBER) AS SPENDING_DIFF
FROM FACT_STORE_SALES
WHERE NET_PAID IS NOT NULL
QUALIFY PREVIOUS_SPENT IS NOT NULL
LIMIT 100;


------------- Graf 6 ------------------------
SELECT
    CUSTOMER_ID,
    TOTAL_SPENT,
    RANK() OVER (ORDER BY TOTAL_SPENT DESC) AS CUSTOMER_RANK
FROM (
    SELECT
        CUSTOMER_ID,
        SUM(NET_PAID) AS TOTAL_SPENT
    FROM FACT_STORE_SALES
    WHERE NET_PAID IS NOT NULL
    GROUP BY CUSTOMER_ID
) t
ORDER BY CUSTOMER_RANK
LIMIT 20;
