USE WAREHOUSE BADGER_WH;
USE DATABASE BADGER_DB;
CREATE OR REPLACE SCHEMA projekt;
USE SCHEMA projekt;

SHOW TABLES IN SCHEMA BADGER_TPCDS_10TB.TPCDS_SF10TCL;

SELECT * FROM badger_tpcds_10tb.tpcds_sf10tcl.customer LIMIT 10;
SELECT * FROM badger_tpcds_10tb.tpcds_sf10tcl.item LIMIT 10;
SELECT * FROM badger_tpcds_10tb.tpcds_sf10tcl.store_sales LIMIT 10;
SELECT * FROM badger_tpcds_10tb.tpcds_sf10tcl.store LIMIT 10;
DESCRIBE TABLE badger_tpcds_10tb.tpcds_sf10tcl.store;

SELECT COUNT(*) FROM badger_tpcds_10tb.tpcds_sf10tcl.store_sales;

---------------------- RAW Tabulky --------------------------------

CREATE OR REPLACE TABLE CUSTOMER (
  CUSTOMER_ID     INT,
  FIRST_NAME      STRING,
  LAST_NAME       STRING,
  EMAIL           STRING,
  BDAY_YEAR       INT,
  COUNTRY         STRING
);

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, BDAY_YEAR, COUNTRY)
SELECT DISTINCT
  C_CUSTOMER_SK        AS CUSTOMER_ID,
  C_FIRST_NAME         AS FIRST_NAME,
  C_LAST_NAME          AS LAST_NAME,
  C_EMAIL_ADDRESS      AS EMAIL,
  C_BIRTH_YEAR         AS BDAY_YEAR,
  C_BIRTH_COUNTRY      AS COUNTRY
FROM BADGER_TPCDS_10TB.TPCDS_SF10TCL.CUSTOMER;

SELECT * FROM CUSTOMER LIMIT 10;
SELECT COUNT(*) FROM CUSTOMER;

CREATE OR REPLACE TABLE STORE (
  STORE_ID           INT,
  NAME               STRING,
  NUMBER_EMPLOYEES   INT,
  START_DATE         DATE,
  COUNTRY            STRING
);

INSERT INTO STORE (STORE_ID, NAME, NUMBER_EMPLOYEES, START_DATE, COUNTRY)
SELECT DISTINCT
  S_STORE_SK                    AS STORE_ID,
  S_STORE_NAME                  AS NAME,
  S_NUMBER_EMPLOYEES            AS NUMBER_EMPLOYEES,
  S_REC_START_DATE              AS START_DATE,
  S_COUNTRY                     AS COUNTRY
FROM BADGER_TPCDS_10TB.TPCDS_SF10TCL.STORE;

SELECT * FROM STORE LIMIT 10;

CREATE OR REPLACE TABLE CATEGORY (
  CATEGORY_ID   INT AUTOINCREMENT,
  NAME          STRING
);

INSERT INTO CATEGORY (NAME)
SELECT DISTINCT I_CATEGORY
FROM BADGER_TPCDS_10TB.TPCDS_SF10TCL.ITEM
WHERE I_CATEGORY IS NOT NULL;

SELECT * FROM CATEGORY;

CREATE OR REPLACE TABLE CLASS (
  CLASS_ID    INT AUTOINCREMENT,
  NAME        STRING
);

INSERT INTO CLASS (NAME)
SELECT DISTINCT I_CLASS
FROM BADGER_TPCDS_10TB.TPCDS_SF10TCL.ITEM
WHERE I_CLASS IS NOT NULL;

SELECT * FROM CLASS LIMIT 10;

CREATE OR REPLACE TABLE ITEM (
  ITEM_ID       INT,
  PRICE         NUMBER(10,2),
  NAME          STRING,
  COLOR         STRING,
  CATEGORY_ID   INT,
  CLASS_ID      INT
);

INSERT INTO ITEM (ITEM_ID, PRICE, NAME, COLOR, CATEGORY_ID, CLASS_ID)
SELECT
  I.I_ITEM_SK                         AS ITEM_ID,
  I.I_CURRENT_PRICE                   AS PRICE,
  I.I_ITEM_DESC                       AS NAME,
  I.I_COLOR                           AS COLOR,
  C.CATEGORY_ID                       AS CATEGORY_ID,
  CL.CLASS_ID                         AS CLASS_ID
FROM BADGER_TPCDS_10TB.TPCDS_SF10TCL.ITEM I
LEFT JOIN CATEGORY C
  ON C.NAME = I.I_CATEGORY
LEFT JOIN CLASS CL
  ON CL.NAME = I.I_CLASS;

SELECT * FROM ITEM LIMIT 10;

CREATE OR REPLACE TABLE STORE_SALES (
  TICKET_NUMBER   INT AUTOINCREMENT,
  QUANTITY        INT,
  SALES_PRICE     NUMBER(10,2),
  COUPON_AMT      NUMBER(10,2),
  NET_PAID        NUMBER(10,2),
  NET_PROFIT      NUMBER(10,2),
  ITEM_ID         INT,
  CUSTOMER_ID     INT,
  STORE_ID        INT
);

INSERT INTO STORE_SALES (QUANTITY, SALES_PRICE, COUPON_AMT, NET_PAID, NET_PROFIT, ITEM_ID, CUSTOMER_ID, STORE_ID)
SELECT
  SS_QUANTITY                 AS QUANTITY,
  SS_SALES_PRICE              AS SALES_PRICE,
  SS_COUPON_AMT               AS COUPON_AMT,
  SS_NET_PAID                 AS NET_PAID,
  SS_NET_PROFIT               AS NET_PROFIT,
  SS_ITEM_SK                  AS ITEM_ID,
  SS_CUSTOMER_SK              AS CUSTOMER_ID,
  SS_STORE_SK                 AS STORE_ID
FROM BADGER_TPCDS_10TB.TPCDS_SF10TCL.STORE_SALES
LIMIT 10000000;

SELECT COUNT(*) FROM STORE_SALES;

----------------------- DIM Tabluky -----------------------------

CREATE OR REPLACE TABLE DIM_CUSTOMER AS
SELECT
  CUSTOMER_ID,
  FIRST_NAME,
  LAST_NAME,
  EMAIL,
  BDAY_YEAR,
  COUNTRY
FROM CUSTOMER;

SELECT * FROM DIM_CUSTOMER LIMIT 10;

CREATE OR REPLACE TABLE DIM_STORE AS
SELECT
  STORE_ID,
  NAME,
  COUNTRY,
  NUMBER_EMPLOYEES,
  START_DATE
FROM STORE;

SELECT * FROM DIM_STORE LIMIT 10;

CREATE OR REPLACE TABLE DIM_ITEM AS
SELECT
  i.ITEM_ID,
  i.PRICE,
  i.NAME,
  i.COLOR,
  c.NAME  AS CATEGORY,
  cl.NAME AS CLASS
FROM ITEM i
LEFT JOIN CATEGORY c
  ON i.CATEGORY_ID = c.CATEGORY_ID
LEFT JOIN CLASS cl
  ON i.CLASS_ID = cl.CLASS_ID;

SELECT * FROM DIM_ITEM LIMIT 10;

CREATE OR REPLACE TABLE DIM_DATE AS
SELECT
  ROW_NUMBER() OVER (ORDER BY D)::INT AS DATE_ID,
  YEAR(D)::INT  AS YEAR,
  MONTH(D)::INT AS MONTH,
  DAY(D)::INT   AS DAY,
  TO_CHAR(D, 'DY') AS WEEKDAY,
  D AS FULL_DATE
FROM (
  SELECT DISTINCT START_DATE AS D
  FROM STORE
  WHERE START_DATE IS NOT NULL
);

SELECT * FROM DIM_DATE;

-------------------- FAKT Tabulka -------------------------------

CREATE OR REPLACE TABLE FACT_STORE_SALES AS
SELECT
  ss.TICKET_NUMBER,
  ss.QUANTITY,
  ss.SALES_PRICE,
  ss.COUPON_AMT,
  ss.NET_PAID,
  ss.NET_PROFIT,
  ss.ITEM_ID,        
  ss.CUSTOMER_ID,
  ss.STORE_ID,    
  d.DATE_ID,
  ROW_NUMBER() OVER (
    PARTITION BY ss.CUSTOMER_ID
    ORDER BY ss.TICKET_NUMBER
  ) AS PURCHASE_SEQ_IN_CUSTOMER,
  LAG(ss.NET_PAID) OVER (
    PARTITION BY ss.CUSTOMER_ID
    ORDER BY ss.TICKET_NUMBER
  ) AS PREV_NET_PAID_CUSTOMER

FROM STORE_SALES ss
LEFT JOIN STORE st
  ON st.STORE_ID = ss.STORE_ID
LEFT JOIN DIM_DATE d
  ON d.FULL_DATE = st.START_DATE;

SELECT * FROM FACT_STORE_SALES LIMIT 10;
